### ISSUE TITLE
Bluray-1080p Remux not listed in sonarr-v4-quality-profile-web-2160p-alternative.yml

### ISSUE THREAD

**Issue by dlmarston** [recyclarr/config-templates#99]
Hi there,

I'm wondering if Bluray-1080p Remux not being listed is a deliberate omission, as it would be handy to have it as part of this template.

sonarr/includes/quality-profiles/sonarr-v4-quality-profile-web-2160p-alternative.yml

**Comment by yammes08** [comment]
> Hi there,
> 
> I'm wondering if Bluray-1080p Remux not being listed is a deliberate omission, as it would be handy to have it as part of this template.
> 
> sonarr/includes/quality-profiles/sonarr-v4-quality-profile-web-2160p-alternative.yml

Hi,

Bluray-1080p Remux is not listed as a quality for this profile on the guides page for this. This is why it is not included here, as these templates mirror the equivalent guide profile.
